from sqlalchemy import (
    Column, Integer, String, Boolean, DateTime, Enum, Text, Numeric,
    ForeignKey, JSON
)
from sqlalchemy.sql import func
from app.database import Base


class Quote(Base):
    __tablename__ = "quotes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    public_token = Column(String(36), unique=True)
    title = Column(String(200))
    client_id = Column(Integer, ForeignKey("clients.id", ondelete="SET NULL"))
    printer_id = Column(Integer, ForeignKey("printers.id"))
    filament_id = Column(Integer, ForeignKey("filaments.id"))
    print_time_hours = Column(Numeric(8, 2), nullable=False)
    filament_used_g = Column(Numeric(10, 2), nullable=False)
    setup_time_hours = Column(Numeric(6, 2), default=0.50)
    post_process_hours = Column(Numeric(6, 2), default=0.00)
    quantity = Column(Integer, default=1)
    energy_kwh_price = Column(Numeric(10, 4))
    labor_hourly_rate = Column(Numeric(10, 2))
    profit_margin_pct = Column(Numeric(5, 2))
    loss_pct = Column(Numeric(5, 2))
    spare_parts_pct = Column(Numeric(5, 2))
    printer_power_watts = Column(Numeric(8, 2))
    printer_purchase_price = Column(Numeric(10, 2))
    printer_lifespan_hours = Column(Integer)
    printer_maintenance_pct = Column(Numeric(5, 2))
    filament_cost_per_kg = Column(Numeric(10, 2))
    cost_filament = Column(Numeric(10, 2), default=0.00)
    cost_energy = Column(Numeric(10, 2), default=0.00)
    cost_depreciation = Column(Numeric(10, 2), default=0.00)
    cost_maintenance = Column(Numeric(10, 2), default=0.00)
    cost_labor = Column(Numeric(10, 2), default=0.00)
    cost_losses = Column(Numeric(10, 2), default=0.00)
    cost_spare_parts = Column(Numeric(10, 2), default=0.00)
    cost_total_production = Column(Numeric(10, 2), default=0.00)
    profit_value = Column(Numeric(10, 2), default=0.00)
    final_price = Column(Numeric(10, 2), default=0.00)
    final_price_per_unit = Column(Numeric(10, 2), default=0.00)
    extras = Column(JSON)
    extras_total = Column(Numeric(10, 2), default=0.00)
    extras_json = Column(JSON)
    tax_pct_applied = Column(Numeric(5, 2), default=0.00)
    tax_amount = Column(Numeric(10, 2), default=0.00)
    discount_value = Column(Numeric(10, 2), default=0.00)
    discount_code = Column(String(100))
    coupon_id = Column(Integer)
    shipping_service = Column(String(100))
    shipping_cost = Column(Numeric(10, 2), default=0.00)
    client_name = Column(String(150))
    client_email = Column(String(150))
    client_phone = Column(String(30))
    client_zipcode = Column(String(20))
    client_address = Column(String(255))
    client_address_number = Column(String(20))
    client_address_comp = Column(String(100))
    client_neighborhood = Column(String(100))
    client_city = Column(String(100))
    client_state = Column(String(10))
    client_document = Column(String(30))
    file_url = Column(Text)
    file_urls = Column(JSON)
    reference_images = Column(JSON)
    result_photo_url = Column(Text)
    show_in_showroom = Column(Boolean, default=False)
    status = Column(
        Enum("quoted", "pending", "approved", "in_production", "delivered",
             "rejected", "cancelled", "counter_offer", "awaiting_payment"),
        default="quoted",
    )
    filament_deducted = Column(Boolean, default=False)
    payment_method = Column(String(50))
    mp_payment_id = Column(String(100))
    pix_qr_code = Column(Text)
    pix_qr_code_base64 = Column(Text)
    platter_id = Column(Integer, ForeignKey("platters.id", ondelete="SET NULL"))
    filament_lot_id = Column(Integer)
    project_id = Column(Integer)
    notes = Column(Text)
    valid_days = Column(Integer, default=30)
    responded_at = Column(DateTime)
    scheduled_start = Column(DateTime)
    scheduled_end = Column(DateTime)
    is_paid = Column(Boolean, default=False)
    paid_at = Column(DateTime)
    credits_used = Column(Numeric(10, 2), default=0.00)
    gcode_url = Column(String(500))
    counter_offer_price = Column(Numeric(10, 2))
    counter_offer_notes = Column(Text)
    is_multicolor = Column(Boolean, default=False)
    items = Column(JSON)
    infill_percentage = Column(Integer, default=20)
    request_type = Column(Enum("stl", "manual"), default="stl")
    nfe_status = Column(String(50))
    nfe_url = Column(String(500))
    melhorenvio_order_id = Column(String(100))
    created_at = Column(DateTime, server_default=func.now())
