ALTER TABLE business_config MODIFY COLUMN company_state VARCHAR(50) DEFAULT NULL;
ALTER TABLE clients MODIFY COLUMN state VARCHAR(50) DEFAULT NULL;
ALTER TABLE quotes MODIFY COLUMN client_state VARCHAR(50) DEFAULT NULL;
ALTER TABLE quote_requests MODIFY COLUMN client_state VARCHAR(50) DEFAULT NULL;
