server {
    listen 80;
    server_name brcprint.com.br www.brcprint.com.br;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name brcprint.com.br www.brcprint.com.br;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/brcprint.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/brcprint.com.br/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;

    # Gzip Compression
    gzip on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_types text/css application/javascript image/svg+xml;

    location /uploads/ {
        alias /var/www/uploads/;
        access_log off;
        expires max;
        add_header Cache-Control public;
    }

    location /outputs/ {
        alias /var/www/outputs/;
        access_log off;
        expires max;
        add_header Cache-Control public;
    }

    location / {
        proxy_pass http://brcprint_app_prod:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
