#!/bin/bash

# brcprint - Automated Deploy Setup for Ubuntu/Debian
# This script installs Docker, auto-generates secure passwords, and launches the stack with SSL via Caddy.

set -e

# Format outputs
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}================================================${NC}"
echo -e "${BLUE}      brcprint - Auto Installer & Deployer        ${NC}"
echo -e "${BLUE}================================================${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Erro: Execute este script como root (sudo ./setup.sh)${NC}"
  exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    if [ "$ID" != "ubuntu" ] && [ "$ID" != "debian" ]; then
        echo -e "${RED}Aviso: Este script foi homologado para Ubuntu/Debian. Pressione CTRL+C para cancelar ou aguarde para arriscar continuar...${NC}"
        sleep 5
    fi
else
    echo -e "${RED}Erro: Não foi possível detectar o OS. Esperado Ubuntu/Debian.${NC}"
    exit 1
fi

echo -e "\n${GREEN}[1/5] Verificando Docker e Docker Compose...${NC}"
if ! command -v docker >/dev/null 2>&1; then
    echo "Docker não encontrado. Instalando..."
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
else
    echo "Docker já instalado."
fi

# -----------------
# -----------------
echo -e "\n${GREEN}[2/5] Coletando Informações da sua Empresa...${NC}"
echo "Isso será usado para gerar seu domínio HTTPS e criar senhas blindadas."

read -p "Qual o domínio que o sistema responderá (ex: cotacao.suaempresa.com.br)? " APP_DOMAIN
read -p "Qual seu e-mail (usado pela Let's Encrypt para avisos de renovação SSL)? " APP_EMAIL

echo -e "\n${GREEN}[3/5] Gerando ambiente seguro no arquivo .env ...${NC}"

# Generate strong random passwords
DB_PASS=$(openssl rand -hex 16)
NEXT_SECRET=$(openssl rand -base64 32)
NEXT_URL="https://${APP_DOMAIN}"

# Ensure directories exist for volumes
mkdir -p public/uploads public/outputs
chmod -R 777 public/uploads public/outputs

cat <<EOF > .env
# Auto-generated by setup.sh
DB_HOST=mysql
DB_PORT=3306
DB_USER=brcprint_user
DB_PASSWORD=${DB_PASS}
DB_NAME=brcprint_db

MYSQL_ROOT_PASSWORD=${DB_PASS}
MYSQL_DATABASE=brcprint_db
MYSQL_USER=brcprint_user
MYSQL_PASSWORD=${DB_PASS}

NEXTAUTH_SECRET=${NEXT_SECRET}
NEXTAUTH_URL=${NEXT_URL}
NEXT_PUBLIC_APP_URL=${NEXT_URL}
NEXT_PUBLIC_BASE_URL=${NEXT_URL}

APP_DOMAIN=${APP_DOMAIN}
APP_EMAIL=${APP_EMAIL}

# ==========================================
# INTEGRAÇÕES OPCIONAIS (Preencha após o deploy se for usar)
# ==========================================
# MERCADOPAGO
MP_ACCESS_TOKEN=
MP_PUBLIC_KEY=

# STRIPE
STRIPE_PUBLIC_KEY=
STRIPE_SECRET_KEY=

# OPENAI (Para BRCPrint Assistant)
OPENAI_API_KEY=
EOF
echo ".env gerado com sucesso contendo senhas criptograficamente fortes."

# -----------------
echo -e "\n${GREEN}[4/5] Configurando o Certificado SSL Automático (Caddy)...${NC}"
cat <<EOF > Caddyfile
${APP_DOMAIN} {
    tls ${APP_EMAIL}

    # Compressão de GZIP default
    encode zstd gzip

    # Roteia requisições do mundo exterior 80/443 para o app Next.js interno na porta 3000
    reverse_proxy brcprint_app_prod:3000
}
EOF
echo "Caddyfile gerado com sucesso apontando para ${APP_DOMAIN}."

# -----------------
echo -e "\n${GREEN}[5/5] Iniciando o brcprint via Docker Compose...${NC}"

chmod +x setup.sh

if docker compose version >/dev/null 2>&1; then
    docker compose -f docker-compose.prod.yml up -d --build
else
    # Fallback to older docker-compose v1
    docker-compose -f docker-compose.prod.yml up -d --build
fi

echo -e "${BLUE}================================================${NC}"
echo -e "${GREEN}Deploy Concluído com Sucesso! 🚀${NC}"
echo -e "Aguarde cerca de 30 a 60 segundos para o banco de dados rodar o init.sql inicial."
echo -e "Acesse seu sistema seguro em: ${GREEN}${NEXT_URL}${NC}"
echo -e "Acesse o Banco de Dados (phpMyAdmin) em: ${GREEN}${NEXT_URL}:8080${NC} (Username: root)"
echo -e "${BLUE}================================================${NC}"
